name:              Cery
highlighter:       pygments
description:       "Management and Reporting for SEM Agencies."
url:               "http://cery.co"

sass:
  sass_dir:        _sass
  style:            :compressed
